# Pytorch Sandbox

This notebook works as a tutorial and laboratory to learn how Pytorch works.

All the theory has been extracted via [Pytoch Documentation](https://docs.pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)

## Tensor

Tensors are similar to ndarrays in numpy but the behaviour behind is different. This is not necessary in this tutorial.

In [2]:
!pip install torch

In [4]:
import torch
import numpy as np

## Tensor Initialization

Tensors could be initialized directly from the data

In [7]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

or from a NumPy array

In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

or from another tensor

In [9]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3823, 0.7622],
        [0.5916, 0.6587]]) 



You can use similiar functions to np.rand(), np.ones and np.zeros in pytorch

In [10]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0379, 0.1887, 0.7696],
        [0.8832, 0.0346, 0.2336]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor attributes

In [11]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Existing over 100 tensor operations, including transposing, indexig, slicing, mathematical operation, linear algebra, random sampling ...

Each of them can be run on the GPU

**Simple Operations**


In [13]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors**

In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Multiplying tensors**

In [15]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


This computes the matrix multiplication between two tensors

In [16]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**In-place Operations**
Operations with a `_` suffix are in-place. For example:

In [20]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with Numpy
### Tensor to Numpy array

In [21]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in tensor it's reflected in the Numpy array

In [22]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### Numpy to Tensor
It's similar

In [23]:
n = np.ones(5)
t = torch.from_numpy(n)

In [24]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


### Example

In [25]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\jvvce/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth


100.0%


In [29]:
prediction = model(data)
prediction

tensor([[-8.6066e-01, -5.7915e-01, -4.3303e-01, -1.6194e+00, -8.0075e-01,
         -2.5564e-01, -5.7937e-01,  1.8135e-01,  1.6789e-01, -1.1248e+00,
         -1.1221e+00, -9.9078e-01, -3.2477e-01, -9.7557e-01, -1.1167e+00,
         -6.0397e-01, -9.0356e-01, -5.7395e-01, -6.7316e-01, -8.3319e-01,
         -1.6487e+00, -8.1565e-01, -1.5255e+00, -8.7485e-03, -1.1222e+00,
         -1.1155e+00, -6.8689e-01, -1.0738e+00, -9.2406e-01, -5.1711e-01,
         -7.1332e-01, -8.4271e-01, -3.6439e-01, -5.0333e-01, -6.0858e-01,
         -3.5510e-01,  5.6211e-01, -5.3577e-01, -4.8964e-01, -7.6052e-02,
         -7.4297e-01, -7.8175e-01, -1.3418e+00, -4.5798e-01, -7.3172e-01,
         -4.1426e-01, -6.8737e-01, -6.0307e-01, -1.3507e+00, -1.2969e+00,
         -5.8138e-01,  2.8619e-01, -4.0543e-01, -5.9689e-01, -3.9072e-01,
         -1.2269e+00, -3.4703e-01, -1.4030e+00, -2.9462e-01, -5.0902e-01,
          7.6445e-01,  2.7941e-02, -1.5535e-01,  2.8750e-02, -8.3111e-01,
         -2.3209e-01, -4.8859e-01, -4.

## Pytorch vs Numpy
### Pytorch

In [30]:
from __future__ import annotations

from typing import Tuple
import torch
import torch.nn as nn
import torch.nn.functional as F


class MLP(nn.Module):
    """
    Simple 2-layer MLP for classification:
    input_dim -> hidden_dim -> num_classes
    ReLU in the hidden layer.
    """

    def __init__(self, input_dim: int, hidden_dim: int, num_classes: int) -> None:
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)   # W1, b1
        self.fc2 = nn.Linear(hidden_dim, num_classes) # W2, b2

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass.
        x: [batch, input_dim]
        returns logits: [batch, num_classes]
        """
        z1 = self.fc1(x)        # [batch, hidden_dim]
        a1 = F.relu(z1)         # ReLU
        logits = self.fc2(a1)   # [batch, num_classes]
        return logits


def compute_loss_and_accuracy(
    model: nn.Module,
    x: torch.Tensor,
    y: torch.Tensor,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Compute cross-entropy loss and accuracy.
    y must be class indices in [0, num_classes-1], shape [batch].
    """
    logits = model(x)  # [batch, num_classes]
    loss = F.cross_entropy(logits, y)

    with torch.no_grad():
        preds = torch.argmax(logits, dim=1)
        acc = (preds == y).float().mean()

    return loss, acc


def train_step(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    x_batch: torch.Tensor,
    y_batch: torch.Tensor,
) -> Tuple[float, float]:
    """
    Performs a single gradient descent step on (x_batch, y_batch).
    Returns (loss_value, accuracy_value) as Python floats.
    """
    model.train()
    optimizer.zero_grad()               # reset gradients
    loss, acc = compute_loss_and_accuracy(model, x_batch, y_batch)
    loss.backward()                     # autograd: dL/dtheta
    optimizer.step()                    # theta <- theta - eta * grad

    return float(loss.item()), float(acc.item())


### Numpy

In [31]:
from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple
import numpy as np


@dataclass
class Params:
    """
    Trainable parameters of the MLP.
    Shapes:
        W1: [input_dim, hidden_dim]
        b1: [hidden_dim]
        W2: [hidden_dim, num_classes]
        b2: [num_classes]
    """
    W1: np.ndarray
    b1: np.ndarray
    W2: np.ndarray
    b2: np.ndarray


@dataclass
class Cache:
    """
    Cache of intermediate values needed for backprop.
    We store:
        X   : [batch, input_dim]
        Z1  : [batch, hidden_dim]
        A1  : [batch, hidden_dim]
        Z2  : [batch, num_classes] (logits)
        P   : [batch, num_classes] (softmax probs)
        y   : [batch] integer labels
    """
    X: np.ndarray
    Z1: np.ndarray
    A1: np.ndarray
    Z2: np.ndarray
    P: np.ndarray
    y: np.ndarray


def relu(x: np.ndarray) -> np.ndarray:
    return np.maximum(0.0, x)


def softmax(logits: np.ndarray) -> np.ndarray:
    """
    Stable softmax:
    subtract max per row to avoid overflow.
    """
    shifted = logits - np.max(logits, axis=1, keepdims=True)
    exp_scores = np.exp(shifted)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
    return probs


def forward_pass(
    X: np.ndarray,
    y: np.ndarray,
    params: Params,
) -> Tuple[float, Cache]:
    """
    Forward pass:
    1) Z1 = X W1 + b1
    2) A1 = ReLU(Z1)
    3) Z2 = A1 W2 + b2
    4) P  = softmax(Z2)
    5) cross-entropy loss

    Returns:
        (loss, cache_for_backprop)
    """
    # Layer 1 (affine)
    Z1 = X @ params.W1 + params.b1  # [N,H]
    A1 = relu(Z1)                   # [N,H]

    # Layer 2 (affine -> logits)
    Z2 = A1 @ params.W2 + params.b2  # [N,C]

    # Softmax
    P = softmax(Z2)  # [N,C]

    # Cross-entropy loss
    N = X.shape[0]
    # log P[i, y_i]
    log_likelihood = -np.log(P[np.arange(N), y])
    loss = np.mean(log_likelihood)

    cache = Cache(
        X=X,
        Z1=Z1,
        A1=A1,
        Z2=Z2,
        P=P,
        y=y,
    )
    return float(loss), cache


def backward_pass(
    params: Params,
    cache: Cache,
) -> Params:
    """
    Computes gradients of the loss w.r.t. parameters.
    Uses formulas derivadas analíticamente.

    Returns:
        grads: Params with dW1, db1, dW2, db2
               (same shapes as params.*)
    """
    X = cache.X        # [N,d_in]
    Z1 = cache.Z1      # [N,H]
    A1 = cache.A1      # [N,H]
    P = cache.P        # [N,C]
    y = cache.y        # [N]

    N = X.shape[0]

    # dZ2 = (P - one_hot(y)) / N
    dZ2 = P.copy()  # [N,C]
    dZ2[np.arange(N), y] -= 1.0
    dZ2 /= N

    # Gradientes capa 2
    dW2 = A1.T @ dZ2                 # [H,C]
    db2 = np.sum(dZ2, axis=0)        # [C]

    # Propagar a capa oculta
    dA1 = dZ2 @ params.W2.T          # [N,H]

    # ReLU backprop: dZ1 = dA1 * 1_{Z1>0}
    dZ1 = dA1 * (Z1 > 0.0)           # [N,H]

    # Gradientes capa 1
    dW1 = X.T @ dZ1                  # [d_in,H]
    db1 = np.sum(dZ1, axis=0)        # [H]

    grads = Params(
        W1=dW1,
        b1=db1,
        W2=dW2,
        b2=db2,
    )
    return grads


def sgd_update(
    params: Params,
    grads: Params,
    lr: float,
) -> Params:
    """
    One SGD step:
    theta <- theta - lr * grad
    """
    params.W1 = params.W1 - lr * grads.W1
    params.b1 = params.b1 - lr * grads.b1
    params.W2 = params.W2 - lr * grads.W2
    params.b2 = params.b2 - lr * grads.b2
    return params


def predict(
    X: np.ndarray,
    params: Params,
) -> np.ndarray:
    """
    Compute class predictions argmax_c softmax(logits)_c.
    """
    Z1 = X @ params.W1 + params.b1
    A1 = relu(Z1)
    Z2 = A1 @ params.W2 + params.b2
    P = softmax(Z2)
    y_hat = np.argmax(P, axis=1)
    return y_hat


In [32]:
torch.manual_seed(1234)
np.random.seed(1234)

batch_size = 8
input_dim = 5
hidden_dim = 7
num_classes = 3
learning_rate = 1e-2

# Numpy
# X_batch: [batch_size, input_dim]
X_batch_np = np.random.randn(batch_size, input_dim).astype(np.float32)
# y_batch: enteros en [0, num_classes-1], shape [batch_size]
y_batch_np = np.random.randint(
    low=0, high=num_classes, size=(batch_size,), dtype=np.int64
)

# Pytorch
X_batch_torch = torch.tensor(X_batch_np)
y_batch_torch = torch.tensor(y_batch_np)

### Initializing

In [33]:
model_torch = MLP(input_dim=input_dim,
                  hidden_dim=hidden_dim,
                  num_classes=num_classes)

optimizer = torch.optim.SGD(model_torch.parameters(),
                            lr=learning_rate)

In [34]:
with torch.no_grad():
    # fc1: Linear(input_dim -> hidden_dim)
    W1_torch = model_torch.fc1.weight.detach().cpu().numpy()  # [hidden_dim, input_dim]
    b1_torch = model_torch.fc1.bias.detach().cpu().numpy()    # [hidden_dim]

    # fc2: Linear(hidden_dim -> num_classes)
    W2_torch = model_torch.fc2.weight.detach().cpu().numpy()  # [num_classes, hidden_dim]
    b2_torch = model_torch.fc2.bias.detach().cpu().numpy()    # [num_classes]

params_np = Params(
    W1=W1_torch.T.copy(),          # [input_dim, hidden_dim]
    b1=b1_torch.copy(),            # [hidden_dim]
    W2=W2_torch.T.copy(),          # [hidden_dim, num_classes]
    b2=b2_torch.copy(),            # [num_classes]
)

In [35]:
# PyTorch
model_torch.eval()
with torch.no_grad():
    logits_torch = model_torch(X_batch_torch)      # [batch, num_classes]
    loss_torch = torch.nn.functional.cross_entropy(
        logits_torch, y_batch_torch
    )
    preds_torch = torch.argmax(logits_torch, dim=1)
    acc_torch = (preds_torch == y_batch_torch).float().mean()

# NumPy
loss_np, cache_np = forward_pass(
    X=X_batch_np,
    y=y_batch_np,
    params=params_np,
)

In [36]:
logits_torch_np = logits_torch.detach().cpu().numpy()  # [batch, num_classes]
# logits = A1 @ W2 + b2  ya está en cache_np.Z2
logits_numpy = cache_np.Z2  # [batch, num_classes]

max_abs_diff_logits = float(
    np.max(np.abs(logits_torch_np - logits_numpy))
)

print("=== FORWARD CHECK ===")
print(f"Loss torch      : {float(loss_torch.item()):.6f}")
print(f"Loss numpy      : {loss_np:.6f}")
print(f"Diff(loss)      : {abs(float(loss_torch.item()) - loss_np):.6e}")
print(f"Acc torch       : {float(acc_torch.item()):.4f}")
print(f"Logits max|Δ|   : {max_abs_diff_logits:.6e}")
print()

=== FORWARD CHECK ===
Loss torch      : 1.102136
Loss numpy      : 1.102136
Diff(loss)      : 0.000000e+00
Acc torch       : 0.5000
Logits max|Δ|   : 5.960464e-08



### Backward and gradient comparation

In [37]:
# Backward PyTorch
model_torch.train()
optimizer.zero_grad()
loss_torch_train, _ = compute_loss_and_accuracy(
    model_torch, X_batch_torch, y_batch_torch
)
loss_torch_train.backward()  # autograd rellena .grad

# Gradientes PyTorch

with torch.no_grad():
    dW1_torch = model_torch.fc1.weight.grad.detach().cpu().numpy()  # [hidden_dim, input_dim]
    db1_torch = model_torch.fc1.bias.grad.detach().cpu().numpy()    # [hidden_dim]
    dW2_torch = model_torch.fc2.weight.grad.detach().cpu().numpy()  # [num_classes, hidden_dim]
    db2_torch = model_torch.fc2.bias.grad.detach().cpu().numpy()    # [num_classes]

# Backward NumPy
grads_np = backward_pass(
    params=params_np,
    cache=cache_np,
)

grad_diffs = {
    "W1": np.max(np.abs(dW1_torch.T - grads_np.W1)),
    "b1": np.max(np.abs(db1_torch   - grads_np.b1)),
    "W2": np.max(np.abs(dW2_torch.T - grads_np.W2)),
    "b2": np.max(np.abs(db2_torch   - grads_np.b2)),
}

print("=== BACKWARD / GRAD CHECK ===")
print(f"max|Δ dW1| : {grad_diffs['W1']:.6e}")
print(f"max|Δ db1| : {grad_diffs['b1']:.6e}")
print(f"max|Δ dW2| : {grad_diffs['W2']:.6e}")
print(f"max|Δ db2| : {grad_diffs['b2']:.6e}")
print()


=== BACKWARD / GRAD CHECK ===
max|Δ dW1| : 1.490116e-08
max|Δ db1| : 7.450581e-09
max|Δ dW2| : 1.676381e-08
max|Δ db2| : 2.980232e-08



One SGD step and new parameters comparation

In [38]:
with torch.no_grad():
    # Clonamos para comparación posterior
    W1_before = model_torch.fc1.weight.detach().cpu().numpy().copy()
    b1_before = model_torch.fc1.bias.detach().cpu().numpy().copy()
    W2_before = model_torch.fc2.weight.detach().cpu().numpy().copy()
    b2_before = model_torch.fc2.bias.detach().cpu().numpy().copy()

optimizer.step()

params_np_after = Params(
    W1=params_np.W1.copy(),
    b1=params_np.b1.copy(),
    W2=params_np.W2.copy(),
    b2=params_np.b2.copy(),
)
params_np_after = sgd_update(
    params=params_np_after,
    grads=grads_np,
    lr=learning_rate,
)

with torch.no_grad():
    W1_after_torch = model_torch.fc1.weight.detach().cpu().numpy()
    b1_after_torch = model_torch.fc1.bias.detach().cpu().numpy()
    W2_after_torch = model_torch.fc2.weight.detach().cpu().numpy()
    b2_after_torch = model_torch.fc2.bias.detach().cpu().numpy()

param_diffs_after = {
    "W1": np.max(np.abs(W1_after_torch.T - params_np_after.W1)),
    "b1": np.max(np.abs(b1_after_torch   - params_np_after.b1)),
    "W2": np.max(np.abs(W2_after_torch.T - params_np_after.W2)),
    "b2": np.max(np.abs(b2_after_torch   - params_np_after.b2)),
}

print("=== PARAM UPDATE CHECK (after one SGD step) ===")
print(f"max|Δ W1| : {param_diffs_after['W1']:.6e}")
print(f"max|Δ b1| : {param_diffs_after['b1']:.6e}")
print(f"max|Δ W2| : {param_diffs_after['W2']:.6e}")
print(f"max|Δ b2| : {param_diffs_after['b2']:.6e}")
print()

=== PARAM UPDATE CHECK (after one SGD step) ===
max|Δ W1| : 0.000000e+00
max|Δ b1| : 0.000000e+00
max|Δ W2| : 2.328306e-10
max|Δ b2| : 0.000000e+00

